cmake_minimum_required(VERSION 3.24)

project(SwiftGameDawn LANGUAGES C CXX)

include(FetchContent)

set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(DAWN_BUILD_MONOLITHIC_LIBRARY STATIC CACHE STRING "" FORCE)
set(DAWN_BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
set(DAWN_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(DAWN_ENABLE_INSTALL ON CACHE BOOL "" FORCE)
set(DAWN_USE_GLFW OFF CACHE BOOL "" FORCE)
set(TINT_BUILD_CMD_TOOLS OFF CACHE BOOL "" FORCE)
set(TINT_BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
set(TINT_BUILD_TESTS OFF CACHE BOOL "" FORCE)

if(APPLE)
    set(DAWN_ENABLE_METAL ON CACHE BOOL "" FORCE)
    set(DAWN_ENABLE_VULKAN OFF CACHE BOOL "" FORCE)
    set(DAWN_ENABLE_D3D12 OFF CACHE BOOL "" FORCE)
    set(DAWN_ENABLE_OPENGLES OFF CACHE BOOL "" FORCE)
elseif(WIN32)
    set(DAWN_ENABLE_METAL OFF CACHE BOOL "" FORCE)
    set(DAWN_ENABLE_VULKAN OFF CACHE BOOL "" FORCE)
    set(DAWN_ENABLE_D3D12 ON CACHE BOOL "" FORCE)
    set(DAWN_ENABLE_OPENGLES OFF CACHE BOOL "" FORCE)
else()
    set(DAWN_ENABLE_METAL OFF CACHE BOOL "" FORCE)
    set(DAWN_ENABLE_VULKAN ON CACHE BOOL "" FORCE)
    set(DAWN_ENABLE_D3D12 OFF CACHE BOOL "" FORCE)
    set(DAWN_ENABLE_OPENGLES ON CACHE BOOL "" FORCE)
endif()

set(DAWN_FETCH_DEPENDENCIES ON CACHE BOOL "" FORCE)

FetchContent_Declare(
    dawn
    GIT_REPOSITORY https://dawn.googlesource.com/dawn
    GIT_TAG 9a18acddc494a7cf5d3aed4bce81eb351ca59904
    GIT_SHALLOW FALSE
    GIT_PROGRESS TRUE
    GIT_SUBMODULES ""
)

FetchContent_MakeAvailable(dawn)

if(DEFINED DAWN_METADATA_DIRECTORY)
    file(MAKE_DIRECTORY "${DAWN_METADATA_DIRECTORY}")
    file(GENERATE
        OUTPUT "${DAWN_METADATA_DIRECTORY}/compiler-flags.txt"
        CONTENT "-I$<JOIN:$<TARGET_PROPERTY:dawn_public_config,INTERFACE_INCLUDE_DIRECTORIES>,\n-I>\n"
    )
    file(GENERATE
        OUTPUT "${DAWN_METADATA_DIRECTORY}/linker-flags.txt"
        CONTENT "$<TARGET_FILE:dawn::webgpu_dawn>\n$<JOIN:$<TARGET_PROPERTY:dawn::webgpu_dawn,INTERFACE_LINK_LIBRARIES>,\n>\n"
    )
endif()
