#include "CSDL3.h"

const SDL_WindowFlags CSDL3_WINDOW_FULLSCREEN = SDL_WINDOW_FULLSCREEN;
const SDL_WindowFlags CSDL3_WINDOW_OPENGL = SDL_WINDOW_OPENGL;
const SDL_WindowFlags CSDL3_WINDOW_OCCLUDED = SDL_WINDOW_OCCLUDED;
const SDL_WindowFlags CSDL3_WINDOW_HIDDEN = SDL_WINDOW_HIDDEN;
const SDL_WindowFlags CSDL3_WINDOW_BORDERLESS = SDL_WINDOW_BORDERLESS;
const SDL_WindowFlags CSDL3_WINDOW_RESIZABLE = SDL_WINDOW_RESIZABLE;
const SDL_WindowFlags CSDL3_WINDOW_MINIMIZED = SDL_WINDOW_MINIMIZED;
const SDL_WindowFlags CSDL3_WINDOW_MAXIMIZED = SDL_WINDOW_MAXIMIZED;
const SDL_WindowFlags CSDL3_WINDOW_MOUSE_GRABBED = SDL_WINDOW_MOUSE_GRABBED;
const SDL_WindowFlags CSDL3_WINDOW_INPUT_FOCUS = SDL_WINDOW_INPUT_FOCUS;
const SDL_WindowFlags CSDL3_WINDOW_MOUSE_FOCUS = SDL_WINDOW_MOUSE_FOCUS;
const SDL_WindowFlags CSDL3_WINDOW_EXTERNAL = SDL_WINDOW_EXTERNAL;
const SDL_WindowFlags CSDL3_WINDOW_MODAL = SDL_WINDOW_MODAL;
const SDL_WindowFlags CSDL3_WINDOW_HIGH_PIXEL_DENSITY = SDL_WINDOW_HIGH_PIXEL_DENSITY;
const SDL_WindowFlags CSDL3_WINDOW_MOUSE_CAPTURE = SDL_WINDOW_MOUSE_CAPTURE;
const SDL_WindowFlags CSDL3_WINDOW_MOUSE_RELATIVE_MODE = SDL_WINDOW_MOUSE_RELATIVE_MODE;
const SDL_WindowFlags CSDL3_WINDOW_ALWAYS_ON_TOP = SDL_WINDOW_ALWAYS_ON_TOP;
const SDL_WindowFlags CSDL3_WINDOW_UTILITY = SDL_WINDOW_UTILITY;
const SDL_WindowFlags CSDL3_WINDOW_TOOLTIP = SDL_WINDOW_TOOLTIP;
const SDL_WindowFlags CSDL3_WINDOW_POPUP_MENU = SDL_WINDOW_POPUP_MENU;
const SDL_WindowFlags CSDL3_WINDOW_KEYBOARD_GRABBED = SDL_WINDOW_KEYBOARD_GRABBED;
const SDL_WindowFlags CSDL3_WINDOW_FILL_DOCUMENT = SDL_WINDOW_FILL_DOCUMENT;
const SDL_WindowFlags CSDL3_WINDOW_VULKAN = SDL_WINDOW_VULKAN;
const SDL_WindowFlags CSDL3_WINDOW_METAL = SDL_WINDOW_METAL;
const SDL_WindowFlags CSDL3_WINDOW_TRANSPARENT = SDL_WINDOW_TRANSPARENT;
const SDL_WindowFlags CSDL3_WINDOW_NOT_FOCUSABLE = SDL_WINDOW_NOT_FOCUSABLE;
